openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    The App for contacts
tags:
  # теги, що ви будете використовувати
  - name: contacts
    description: operations about contacts.
  - name: auth
    description: auth operations
servers:
  - url: http://localhost:3000
  - url: #посилання на задеплоєний сайт
paths:
  # Посилання на ендпоінти
  /contacts/{}:
    get:
      $ref: ../swager/paths/contacts/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer